// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: session/v1/session.proto

// Package session.v1 is the MCP session row: the value stored in the session
// key space.
//
// A session is canonical but expendable (plan §II.2): losing one costs a client
// a re-initialise, not data. It is stored rather than held in memory anyway,
// because the alternative strands every connected agent on a rolling restart —
// and a row per session is a rounding error against the memories beside it.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session is one MCP session.
//
// The tenant is deliberately absent: it is in the key, and a second copy inside
// the value is a second thing that can disagree with the first.
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// principal names the credential that opened the session, for audit. It is
	// never the secret.
	Principal string `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	// client_name and client_version are what the client called itself at
	// initialize. They are the only way to answer "which agent is doing this"
	// when one starts misbehaving.
	ClientName    *string `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3,oneof" json:"client_name,omitempty"`
	ClientVersion *string `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3,oneof" json:"client_version,omitempty"`
	// protocol_version is the version negotiated at initialize, so a session
	// opened by an older client keeps being answered the way it expects.
	ProtocolVersion  string `protobuf:"bytes,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	CreatedAtUnixMs  uint64 `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	LastSeenAtUnixMs uint64 `protobuf:"varint,6,opt,name=last_seen_at_unix_ms,json=lastSeenAtUnixMs,proto3" json:"last_seen_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_session_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *Session) GetClientName() string {
	if x != nil && x.ClientName != nil {
		return *x.ClientName
	}
	return ""
}

func (x *Session) GetClientVersion() string {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return ""
}

func (x *Session) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Session) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Session) GetLastSeenAtUnixMs() uint64 {
	if x != nil {
		return x.LastSeenAtUnixMs
	}
	return 0
}

var File_session_v1_session_proto protoreflect.FileDescriptor

const file_session_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x18session/v1/session.proto\x12\n" +
	"session.v1\"\xa4\x02\n" +
	"\aSession\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12$\n" +
	"\vclient_name\x18\x02 \x01(\tH\x00R\n" +
	"clientName\x88\x01\x01\x12*\n" +
	"\x0eclient_version\x18\x03 \x01(\tH\x01R\rclientVersion\x88\x01\x01\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\tR\x0fprotocolVersion\x12+\n" +
	"\x12created_at_unix_ms\x18\x05 \x01(\x04R\x0fcreatedAtUnixMs\x12.\n" +
	"\x14last_seen_at_unix_ms\x18\x06 \x01(\x04R\x10lastSeenAtUnixMsB\x0e\n" +
	"\f_client_nameB\x11\n" +
	"\x0f_client_versionB6Z4github.com/remem-org/remem-go/internal/session/pb;pbb\x06proto3"

var (
	file_session_v1_session_proto_rawDescOnce sync.Once
	file_session_v1_session_proto_rawDescData []byte
)

func file_session_v1_session_proto_rawDescGZIP() []byte {
	file_session_v1_session_proto_rawDescOnce.Do(func() {
		file_session_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_v1_session_proto_rawDesc), len(file_session_v1_session_proto_rawDesc)))
	})
	return file_session_v1_session_proto_rawDescData
}

var file_session_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_session_v1_session_proto_goTypes = []any{
	(*Session)(nil), // 0: session.v1.Session
}
var file_session_v1_session_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_session_v1_session_proto_init() }
func file_session_v1_session_proto_init() {
	if File_session_v1_session_proto != nil {
		return
	}
	file_session_v1_session_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_v1_session_proto_rawDesc), len(file_session_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_v1_session_proto_goTypes,
		DependencyIndexes: file_session_v1_session_proto_depIdxs,
		MessageInfos:      file_session_v1_session_proto_msgTypes,
	}.Build()
	File_session_v1_session_proto = out.File
	file_session_v1_session_proto_goTypes = nil
	file_session_v1_session_proto_depIdxs = nil
}
