// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: schema/v1/schema.proto

// Package schema.v1 is the durable state of Remem's own evolution: the
// registered attribute slot table, and the record of every migration that has
// run against a directory.
//
// Both are untenanted system rows, and both are bare protobuf rather than
// codec-enveloped values — the envelope in internal/codec frames the record key
// space, and a system row is not a record. The convention matches
// proto/tenant/v1: field-number evolution is what lets an older binary read a
// row a newer one wrote, and preserve the fields it never heard of when it
// writes that row back.
//
// The same rules apply here as to every other durable schema in this
// repository: a field number is never reused for a different meaning, fields
// are only added or reserved, and `optional` is used wherever absence is
// meaningful.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SlotType is an attribute's storage type.
//
// The fixed-width types are Rust Remem's, with their numbers chosen so an
// imported corpus needs no remapping. STRING is the one addition, and it is
// variable-width: a row carrying one length-prefixes it, so skipping past an
// unknown slot still works.
type SlotType int32

const (
	SlotType_SLOT_TYPE_UNSPECIFIED SlotType = 0
	SlotType_SLOT_TYPE_BOOL        SlotType = 1
	SlotType_SLOT_TYPE_U8          SlotType = 2
	SlotType_SLOT_TYPE_U32         SlotType = 3
	SlotType_SLOT_TYPE_U64         SlotType = 4
	SlotType_SLOT_TYPE_F32         SlotType = 5
	SlotType_SLOT_TYPE_STRING      SlotType = 6
)

// Enum value maps for SlotType.
var (
	SlotType_name = map[int32]string{
		0: "SLOT_TYPE_UNSPECIFIED",
		1: "SLOT_TYPE_BOOL",
		2: "SLOT_TYPE_U8",
		3: "SLOT_TYPE_U32",
		4: "SLOT_TYPE_U64",
		5: "SLOT_TYPE_F32",
		6: "SLOT_TYPE_STRING",
	}
	SlotType_value = map[string]int32{
		"SLOT_TYPE_UNSPECIFIED": 0,
		"SLOT_TYPE_BOOL":        1,
		"SLOT_TYPE_U8":          2,
		"SLOT_TYPE_U32":         3,
		"SLOT_TYPE_U64":         4,
		"SLOT_TYPE_F32":         5,
		"SLOT_TYPE_STRING":      6,
	}
)

func (x SlotType) Enum() *SlotType {
	p := new(SlotType)
	*p = x
	return p
}

func (x SlotType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_v1_schema_proto_enumTypes[0].Descriptor()
}

func (SlotType) Type() protoreflect.EnumType {
	return &file_schema_v1_schema_proto_enumTypes[0]
}

func (x SlotType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotType.Descriptor instead.
func (SlotType) EnumDescriptor() ([]byte, []int) {
	return file_schema_v1_schema_proto_rawDescGZIP(), []int{0}
}

type MigrationState_State int32

const (
	MigrationState_STATE_UNSPECIFIED MigrationState_State = 0
	// PENDING: planned, not yet started.
	MigrationState_STATE_PENDING MigrationState_State = 1
	// RUNNING: started and not finished. A row left in this state is what a
	// crash looks like, and it is what the runner resumes from.
	MigrationState_STATE_RUNNING MigrationState_State = 2
	// DONE: terminal and successful.
	MigrationState_STATE_DONE MigrationState_State = 3
	// FAILED: the last attempt returned an error. Retried on the next open.
	MigrationState_STATE_FAILED MigrationState_State = 4
)

// Enum value maps for MigrationState_State.
var (
	MigrationState_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_RUNNING",
		3: "STATE_DONE",
		4: "STATE_FAILED",
	}
	MigrationState_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_RUNNING":     2,
		"STATE_DONE":        3,
		"STATE_FAILED":      4,
	}
)

func (x MigrationState_State) Enum() *MigrationState_State {
	p := new(MigrationState_State)
	*p = x
	return p
}

func (x MigrationState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_v1_schema_proto_enumTypes[1].Descriptor()
}

func (MigrationState_State) Type() protoreflect.EnumType {
	return &file_schema_v1_schema_proto_enumTypes[1]
}

func (x MigrationState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationState_State.Descriptor instead.
func (MigrationState_State) EnumDescriptor() ([]byte, []int) {
	return file_schema_v1_schema_proto_rawDescGZIP(), []int{2, 0}
}

// SlotSchema is the registered attribute slot table: the value stored at the
// untenanted system key /slots.
//
// It is canonical data in the strict sense — losing it does not lose a memory,
// but it loses the ability to decode every attribute row on disk, because an
// attribute row is a packed blob whose fields are addressed by slot number and
// skipped by declared width. The table is what turns those bytes back into
// named values.
type SlotSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the schema's own revision, bumped whenever a slot is added or
	// retired. It is not a storage format version and not a tenant's user-schema
	// version; it exists so an operator can see that the table moved.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// slots are the declarations, in no guaranteed order. Readers index by slot
	// number; the writer sorts for a stable byte representation.
	Slots         []*Slot `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotSchema) Reset() {
	*x = SlotSchema{}
	mi := &file_schema_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotSchema) ProtoMessage() {}

func (x *SlotSchema) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotSchema.ProtoReflect.Descriptor instead.
func (*SlotSchema) Descriptor() ([]byte, []int) {
	return file_schema_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *SlotSchema) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SlotSchema) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

// Slot is one attribute's declaration.
//
// A slot number is never reused and a slot is never dropped — it is retired,
// which keeps its declared type on disk so that rows written before the
// retirement can still be decoded. The type is what gives a reader the width to
// skip past a value it no longer has a name for.
type Slot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// slot is the number. It is a uint16 in Go; proto3 has no narrower integer
	// than uint32, and the Go side refuses anything that will not fit.
	Slot uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// name is what the field is called. It is part of the compatibility surface:
	// renaming a slot is refused, because the name is how callers address it and
	// a silent rename would repoint every query at a different column.
	Name string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type SlotType `protobuf:"varint,3,opt,name=type,proto3,enum=schema.v1.SlotType" json:"type,omitempty"`
	// indexed is whether this slot carries an ordered index usable as an access
	// path. A retired slot has no index whatever this says.
	Indexed bool `protobuf:"varint,4,opt,name=indexed,proto3" json:"indexed,omitempty"`
	// retired means the slot is never written to new rows. Its declaration
	// survives so older rows stay decodable.
	Retired       bool `protobuf:"varint,5,opt,name=retired,proto3" json:"retired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_schema_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_schema_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Slot) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Slot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Slot) GetType() SlotType {
	if x != nil {
		return x.Type
	}
	return SlotType_SLOT_TYPE_UNSPECIFIED
}

func (x *Slot) GetIndexed() bool {
	if x != nil {
		return x.Indexed
	}
	return false
}

func (x *Slot) GetRetired() bool {
	if x != nil {
		return x.Retired
	}
	return false
}

// MigrationState is the durable record of one migration: the value stored at
// the untenanted system key /migration/<id>.
//
// The fields are spec §20.3's, and no more. It exists so that a migration
// interrupted by a process restart, a node restart or a cluster failover can be
// resumed exactly rather than restarted approximately — which for a step that
// walks a corpus is the difference between minutes and hours, and for a step
// that is not idempotent is the difference between correct and not.
type MigrationState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// migration_id is the step's stable id. It is also in the key; the copy here
	// is what lets a state row be exported and still say what it is about.
	MigrationId string `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	// source_format and target_format are the subsystem versions the step moves
	// between, captured when it started. They are recorded rather than looked up
	// so that a resumed run can tell it is resuming the same work: a binary
	// upgraded mid-migration would otherwise silently continue a step under new
	// assumptions.
	SourceFormat map[string]uint32    `protobuf:"bytes,2,rep,name=source_format,json=sourceFormat,proto3" json:"source_format,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TargetFormat map[string]uint32    `protobuf:"bytes,3,rep,name=target_format,json=targetFormat,proto3" json:"target_format,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	State        MigrationState_State `protobuf:"varint,4,opt,name=state,proto3,enum=schema.v1.MigrationState_State" json:"state,omitempty"`
	// cursor is where the last checkpoint left off, opaque to everything but the
	// step that wrote it. It is committed in the same transaction as the work it
	// describes, so it never points past unfinished work.
	Cursor               []byte `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	ProcessedCount       uint64 `protobuf:"varint,6,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	StartedAtUnixMs      uint64 `protobuf:"varint,7,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	LastProgressAtUnixMs uint64 `protobuf:"varint,8,opt,name=last_progress_at_unix_ms,json=lastProgressAtUnixMs,proto3" json:"last_progress_at_unix_ms,omitempty"`
	// error is the failure that stopped the last attempt, kept so an operator
	// finds out why without the log that carried it. Empty unless state is
	// FAILED.
	Error         string `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationState) Reset() {
	*x = MigrationState{}
	mi := &file_schema_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationState) ProtoMessage() {}

func (x *MigrationState) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationState.ProtoReflect.Descriptor instead.
func (*MigrationState) Descriptor() ([]byte, []int) {
	return file_schema_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *MigrationState) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *MigrationState) GetSourceFormat() map[string]uint32 {
	if x != nil {
		return x.SourceFormat
	}
	return nil
}

func (x *MigrationState) GetTargetFormat() map[string]uint32 {
	if x != nil {
		return x.TargetFormat
	}
	return nil
}

func (x *MigrationState) GetState() MigrationState_State {
	if x != nil {
		return x.State
	}
	return MigrationState_STATE_UNSPECIFIED
}

func (x *MigrationState) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *MigrationState) GetProcessedCount() uint64 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *MigrationState) GetStartedAtUnixMs() uint64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *MigrationState) GetLastProgressAtUnixMs() uint64 {
	if x != nil {
		return x.LastProgressAtUnixMs
	}
	return 0
}

func (x *MigrationState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_schema_v1_schema_proto protoreflect.FileDescriptor

const file_schema_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x16schema/v1/schema.proto\x12\tschema.v1\"M\n" +
	"\n" +
	"SlotSchema\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12%\n" +
	"\x05slots\x18\x02 \x03(\v2\x0f.schema.v1.SlotR\x05slots\"\x8b\x01\n" +
	"\x04Slot\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.schema.v1.SlotTypeR\x04type\x12\x18\n" +
	"\aindexed\x18\x04 \x01(\bR\aindexed\x12\x18\n" +
	"\aretired\x18\x05 \x01(\bR\aretired\"\xb4\x05\n" +
	"\x0eMigrationState\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\x12P\n" +
	"\rsource_format\x18\x02 \x03(\v2+.schema.v1.MigrationState.SourceFormatEntryR\fsourceFormat\x12P\n" +
	"\rtarget_format\x18\x03 \x03(\v2+.schema.v1.MigrationState.TargetFormatEntryR\ftargetFormat\x125\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1f.schema.v1.MigrationState.StateR\x05state\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\fR\x06cursor\x12'\n" +
	"\x0fprocessed_count\x18\x06 \x01(\x04R\x0eprocessedCount\x12+\n" +
	"\x12started_at_unix_ms\x18\a \x01(\x04R\x0fstartedAtUnixMs\x126\n" +
	"\x18last_progress_at_unix_ms\x18\b \x01(\x04R\x14lastProgressAtUnixMs\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x1a?\n" +
	"\x11SourceFormatEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a?\n" +
	"\x11TargetFormatEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"f\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x02\x12\x0e\n" +
	"\n" +
	"STATE_DONE\x10\x03\x12\x10\n" +
	"\fSTATE_FAILED\x10\x04*\x9a\x01\n" +
	"\bSlotType\x12\x19\n" +
	"\x15SLOT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSLOT_TYPE_BOOL\x10\x01\x12\x10\n" +
	"\fSLOT_TYPE_U8\x10\x02\x12\x11\n" +
	"\rSLOT_TYPE_U32\x10\x03\x12\x11\n" +
	"\rSLOT_TYPE_U64\x10\x04\x12\x11\n" +
	"\rSLOT_TYPE_F32\x10\x05\x12\x14\n" +
	"\x10SLOT_TYPE_STRING\x10\x06B5Z3github.com/remem-org/remem-go/internal/schema/pb;pbb\x06proto3"

var (
	file_schema_v1_schema_proto_rawDescOnce sync.Once
	file_schema_v1_schema_proto_rawDescData []byte
)

func file_schema_v1_schema_proto_rawDescGZIP() []byte {
	file_schema_v1_schema_proto_rawDescOnce.Do(func() {
		file_schema_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_v1_schema_proto_rawDesc), len(file_schema_v1_schema_proto_rawDesc)))
	})
	return file_schema_v1_schema_proto_rawDescData
}

var file_schema_v1_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_schema_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_schema_v1_schema_proto_goTypes = []any{
	(SlotType)(0),             // 0: schema.v1.SlotType
	(MigrationState_State)(0), // 1: schema.v1.MigrationState.State
	(*SlotSchema)(nil),        // 2: schema.v1.SlotSchema
	(*Slot)(nil),              // 3: schema.v1.Slot
	(*MigrationState)(nil),    // 4: schema.v1.MigrationState
	nil,                       // 5: schema.v1.MigrationState.SourceFormatEntry
	nil,                       // 6: schema.v1.MigrationState.TargetFormatEntry
}
var file_schema_v1_schema_proto_depIdxs = []int32{
	3, // 0: schema.v1.SlotSchema.slots:type_name -> schema.v1.Slot
	0, // 1: schema.v1.Slot.type:type_name -> schema.v1.SlotType
	5, // 2: schema.v1.MigrationState.source_format:type_name -> schema.v1.MigrationState.SourceFormatEntry
	6, // 3: schema.v1.MigrationState.target_format:type_name -> schema.v1.MigrationState.TargetFormatEntry
	1, // 4: schema.v1.MigrationState.state:type_name -> schema.v1.MigrationState.State
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_schema_v1_schema_proto_init() }
func file_schema_v1_schema_proto_init() {
	if File_schema_v1_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_v1_schema_proto_rawDesc), len(file_schema_v1_schema_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_v1_schema_proto_goTypes,
		DependencyIndexes: file_schema_v1_schema_proto_depIdxs,
		EnumInfos:         file_schema_v1_schema_proto_enumTypes,
		MessageInfos:      file_schema_v1_schema_proto_msgTypes,
	}.Build()
	File_schema_v1_schema_proto = out.File
	file_schema_v1_schema_proto_goTypes = nil
	file_schema_v1_schema_proto_depIdxs = nil
}
