// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: record/v1/record.proto

// Package record.v1 is the canonical record body: the bytes inside every value
// in the record key space, wrapped by the envelope internal/codec writes.
//
// Protobuf is the body encoding for one reason (plan §II.3): field-number
// evolution is the only option that lets this binary decode a record written by
// a version that did not exist when it was compiled, and preserve the fields it
// does not understand when it writes that record back. A rolling upgrade
// depends on that; speed did not enter into it (spec §41).
//
// Rules, which are compatibility guarantees and not style:
//   - a field number is never reused for a different meaning;
//   - fields are only added or reserved, never repurposed;
//   - `optional` wherever absence is meaningful, so "unset" and "zero" stay
//     distinguishable;
//   - schema_version travels inside the body so a record says which schema
//     wrote it, independent of the storage format version (plan §II.5b).
//
// Field number ranges, so later phases do not collide:
//   1-19   identity and content        (this phase)
//   20-49  lifecycle and retention     (Phase 4, plan §II.6)
//   50-79  attributes and user fields
//   80-99  reserved for experiments that must never reach a release

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordType int32

const (
	RecordType_RECORD_TYPE_UNSPECIFIED RecordType = 0
	RecordType_RECORD_TYPE_MEMORY      RecordType = 1
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "RECORD_TYPE_UNSPECIFIED",
		1: "RECORD_TYPE_MEMORY",
	}
	RecordType_value = map[string]int32{
		"RECORD_TYPE_UNSPECIFIED": 0,
		"RECORD_TYPE_MEMORY":      1,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_record_v1_record_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_record_v1_record_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_record_v1_record_proto_rawDescGZIP(), []int{0}
}

// Record is a canonical record body.
//
// The tenant and namespace are deliberately absent: they are in the key, and a
// second copy inside the value is a second thing that can disagree with the
// first. The id is present despite also being in the key, because an export
// carries bodies without their keys and because it lets a read check that the
// row it decoded is the row it asked for.
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the 16-byte UUID. v7 for records this binary creates, v4 for those
	// imported from Rust Remem.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// schema_version is the tenant's user-schema version at the time of writing.
	// It is not the storage format version and must never be confused with it —
	// a Phase 4 test asserts that moving one leaves the other unmoved.
	SchemaVersion uint32 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// type distinguishes the kinds of record sharing the record space. It
	// mirrors keys.RecordType, which is the byte the key sorts on.
	Type RecordType `protobuf:"varint,3,opt,name=type,proto3,enum=record.v1.RecordType" json:"type,omitempty"`
	// content is the memory text.
	Content         string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAtUnixMs uint64 `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs uint64 `protobuf:"varint,6,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	// tags are ordinary terms in the text index rather than a special case
	// (plan §II.10 row 2).
	Tags []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// source is where the memory came from. Absent means unrecorded, which is
	// different from recorded as empty.
	Source *string `protobuf:"bytes,8,opt,name=source,proto3,oneof" json:"source,omitempty"`
	// archived retires a memory from retrieval without deleting it. The record,
	// its indexes and its export entry all survive until cleanup: a heuristic
	// must never destroy user data (plan §II.10 row 8), and "why did my memory
	// disappear" has to have an answer other than "it did not".
	Archived bool `protobuf:"varint,20,opt,name=archived,proto3" json:"archived,omitempty"`
	// archived_at_unix_ms is when it was retired. Absent while live.
	ArchivedAtUnixMs *uint64 `protobuf:"varint,21,opt,name=archived_at_unix_ms,json=archivedAtUnixMs,proto3,oneof" json:"archived_at_unix_ms,omitempty"`
	// policy is the named retention policy: "short_term", "long_term" or
	// "pinned" (plan §II.6). It replaces Rust's MemoryType enum, so that adding
	// a retention behaviour is data rather than a new variant every match arm
	// has to learn about. Empty means the default policy in force.
	Policy string `protobuf:"bytes,22,opt,name=policy,proto3" json:"policy,omitempty"`
	// importance is the record's weight in ranking and in decay, 0..1.
	Importance float32 `protobuf:"fixed32,23,opt,name=importance,proto3" json:"importance,omitempty"`
	// health is the decay budget, 0..100, matching Rust's scale so an imported
	// corpus needs no rescaling. Zero always archives (plan §II.10 row 8).
	Health float32 `protobuf:"fixed32,24,opt,name=health,proto3" json:"health,omitempty"`
	// emotional_valence (-1..1) and arousal (0..1) are the affective dimensions
	// Rust records. Nothing reads them before Phase 10; they are written now so
	// an import has somewhere to put them.
	EmotionalValence float32 `protobuf:"fixed32,25,opt,name=emotional_valence,json=emotionalValence,proto3" json:"emotional_valence,omitempty"`
	Arousal          float32 `protobuf:"fixed32,26,opt,name=arousal,proto3" json:"arousal,omitempty"`
	// accessed_at_unix_ms and access_count are read telemetry. A read updates
	// them in Phase 10, through the durable event stream (plan §II.10 row 4).
	AccessedAtUnixMs uint64 `protobuf:"varint,27,opt,name=accessed_at_unix_ms,json=accessedAtUnixMs,proto3" json:"accessed_at_unix_ms,omitempty"`
	AccessCount      uint32 `protobuf:"varint,28,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	// last_recalled_at_unix_ms is the last *genuine* recall, which is not every
	// access: it is absent until one happens, and absent is different from the
	// epoch.
	LastRecalledAtUnixMs *uint64 `protobuf:"varint,29,opt,name=last_recalled_at_unix_ms,json=lastRecalledAtUnixMs,proto3,oneof" json:"last_recalled_at_unix_ms,omitempty"`
	// next_attention_at_unix_ms is when a lifecycle sweep next needs to look at
	// this record — one value shared by every sweep rather than one index per
	// sweep. Zero means "due now", which is the safe reading of a record nothing
	// has scheduled yet: treating it as "never" would drop the record out of
	// maintenance silently and permanently.
	//
	// It is derived: internal/lifecycle recomputes it from the fields below on
	// every write, and it is stored here as well as in attribute slot 9 so that
	// the body and the row a listing walks cannot disagree about the same
	// memory. Nothing reads it back to decide anything.
	NextAttentionAtUnixMs uint64 `protobuf:"varint,30,opt,name=next_attention_at_unix_ms,json=nextAttentionAtUnixMs,proto3" json:"next_attention_at_unix_ms,omitempty"`
	// ttl_secs is how long this memory lives before it expires. Absent means it
	// never does, which is Rust's behaviour and not plan §II.6's: a short-term
	// memory without a TTL is retired by health, not by the clock
	// (services/types.rs:1139-1143).
	//
	// Seconds rather than milliseconds, matching Rust, so an import is a copy
	// rather than a conversion that can round.
	TtlSecs *uint64 `protobuf:"varint,31,opt,name=ttl_secs,json=ttlSecs,proto3,oneof" json:"ttl_secs,omitempty"`
	// protected_until_unix_ms defers decay and forgetting wholesale while it is
	// in the future. It is what Rust calls flashbulb_until: a memory stored with
	// arousal >= 0.8 is protected for thirty days (services/memory_manager.rs:115).
	//
	// Plan §II.6 expresses this as a temporary `pinned` policy that reverts.
	// Doing that needs two more durable fields — what to revert to, and when —
	// to say what this one timestamp says, and it would make a record's policy a
	// value that changes by itself, which nothing else in the system does.
	ProtectedUntilUnixMs *uint64 `protobuf:"varint,32,opt,name=protected_until_unix_ms,json=protectedUntilUnixMs,proto3,oneof" json:"protected_until_unix_ms,omitempty"`
	// last_decay_at_unix_ms is when importance decay last ran. Absent means
	// never, and the decay clock then starts at created_at
	// (services/lifecycle_manager.rs:275-278).
	LastDecayAtUnixMs *uint64 `protobuf:"varint,33,opt,name=last_decay_at_unix_ms,json=lastDecayAtUnixMs,proto3,oneof" json:"last_decay_at_unix_ms,omitempty"`
	// last_health_check_at_unix_ms is when active forgetting last ran. It is a
	// separate field from last_decay_at because Rust advances the two on
	// different passes, and the differential harness compares both.
	LastHealthCheckAtUnixMs *uint64 `protobuf:"varint,34,opt,name=last_health_check_at_unix_ms,json=lastHealthCheckAtUnixMs,proto3,oneof" json:"last_health_check_at_unix_ms,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_record_v1_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_record_v1_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_record_v1_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Record) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Record) GetType() RecordType {
	if x != nil {
		return x.Type
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *Record) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Record) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Record) GetUpdatedAtUnixMs() uint64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *Record) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Record) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Record) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Record) GetArchivedAtUnixMs() uint64 {
	if x != nil && x.ArchivedAtUnixMs != nil {
		return *x.ArchivedAtUnixMs
	}
	return 0
}

func (x *Record) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *Record) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Record) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Record) GetEmotionalValence() float32 {
	if x != nil {
		return x.EmotionalValence
	}
	return 0
}

func (x *Record) GetArousal() float32 {
	if x != nil {
		return x.Arousal
	}
	return 0
}

func (x *Record) GetAccessedAtUnixMs() uint64 {
	if x != nil {
		return x.AccessedAtUnixMs
	}
	return 0
}

func (x *Record) GetAccessCount() uint32 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

func (x *Record) GetLastRecalledAtUnixMs() uint64 {
	if x != nil && x.LastRecalledAtUnixMs != nil {
		return *x.LastRecalledAtUnixMs
	}
	return 0
}

func (x *Record) GetNextAttentionAtUnixMs() uint64 {
	if x != nil {
		return x.NextAttentionAtUnixMs
	}
	return 0
}

func (x *Record) GetTtlSecs() uint64 {
	if x != nil && x.TtlSecs != nil {
		return *x.TtlSecs
	}
	return 0
}

func (x *Record) GetProtectedUntilUnixMs() uint64 {
	if x != nil && x.ProtectedUntilUnixMs != nil {
		return *x.ProtectedUntilUnixMs
	}
	return 0
}

func (x *Record) GetLastDecayAtUnixMs() uint64 {
	if x != nil && x.LastDecayAtUnixMs != nil {
		return *x.LastDecayAtUnixMs
	}
	return 0
}

func (x *Record) GetLastHealthCheckAtUnixMs() uint64 {
	if x != nil && x.LastHealthCheckAtUnixMs != nil {
		return *x.LastHealthCheckAtUnixMs
	}
	return 0
}

// Vector is a canonical embedding: the value stored in the vector key space.
//
// model_id and dim travel with every vector because nothing in Rust Remem
// recorded which model produced one (plan §II.10 row 10), and a model change
// therefore corrupted the space silently — the vectors stayed the right shape
// and stopped meaning the same thing. A vector whose model_id is not the
// running model's is refused, not scored.
type Vector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// model_id names the model that produced the values, e.g. all-MiniLM-L6-v2.
	ModelId string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// dim is the vector width. It is stored as well as implied by values so a
	// truncated value is detectable rather than merely shorter.
	Dim uint32 `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	// values are the components, L2-normalised at the embedder.
	Values        []float32 `protobuf:"fixed32,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_record_v1_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_record_v1_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_record_v1_record_proto_rawDescGZIP(), []int{1}
}

func (x *Vector) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *Vector) GetDim() uint32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// Edge is a relationship between two records: the value stored in the out-edge
// key space, and copied verbatim into the derived in-edge index.
//
// It carries only what the key does not. The tenant, the namespace, both
// endpoints and the relationship type are all in the key, and a second copy in
// the value is a second thing that can disagree with the first — the same rule
// Record follows for tenant and namespace.
//
// The copy in the in-edge index is what makes "what points at this memory, with
// what strength" one iterator rather than one read per neighbour. The price is
// that this message must marshal deterministically, because a rebuild of that
// index is required to reproduce it byte for byte, and `meta` is a map: Go's
// protobuf runtime randomises map field order unless it is told not to. See
// codec.MarshalEdge.
type Edge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// strength is the weight the relationship carries, 0..1. For an
	// auto-discovered edge it is the similarity that discovered it; for a
	// user-created one it is stated confidence. Traversal ranks by the product of
	// these along a path, which is what plan §II.10 row 7 (REM-83) asks for.
	Strength        float32 `protobuf:"fixed32,1,opt,name=strength,proto3" json:"strength,omitempty"`
	CreatedAtUnixMs uint64  `protobuf:"varint,2,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs uint64  `protobuf:"varint,3,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	// meta is caller-supplied annotation. It is opaque to Remem: nothing indexes
	// it, nothing ranks by it, and it survives a round trip unchanged.
	Meta          map[string]string `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_record_v1_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_record_v1_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_record_v1_record_proto_rawDescGZIP(), []int{2}
}

func (x *Edge) GetStrength() float32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Edge) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Edge) GetUpdatedAtUnixMs() uint64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *Edge) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_record_v1_record_proto protoreflect.FileDescriptor

const file_record_v1_record_proto_rawDesc = "" +
	"\n" +
	"\x16record/v1/record.proto\x12\trecord.v1\"\xba\b\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.record.v1.RecordTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12+\n" +
	"\x12created_at_unix_ms\x18\x05 \x01(\x04R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\x06 \x01(\x04R\x0fupdatedAtUnixMs\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1b\n" +
	"\x06source\x18\b \x01(\tH\x00R\x06source\x88\x01\x01\x12\x1a\n" +
	"\barchived\x18\x14 \x01(\bR\barchived\x122\n" +
	"\x13archived_at_unix_ms\x18\x15 \x01(\x04H\x01R\x10archivedAtUnixMs\x88\x01\x01\x12\x16\n" +
	"\x06policy\x18\x16 \x01(\tR\x06policy\x12\x1e\n" +
	"\n" +
	"importance\x18\x17 \x01(\x02R\n" +
	"importance\x12\x16\n" +
	"\x06health\x18\x18 \x01(\x02R\x06health\x12+\n" +
	"\x11emotional_valence\x18\x19 \x01(\x02R\x10emotionalValence\x12\x18\n" +
	"\aarousal\x18\x1a \x01(\x02R\aarousal\x12-\n" +
	"\x13accessed_at_unix_ms\x18\x1b \x01(\x04R\x10accessedAtUnixMs\x12!\n" +
	"\faccess_count\x18\x1c \x01(\rR\vaccessCount\x12;\n" +
	"\x18last_recalled_at_unix_ms\x18\x1d \x01(\x04H\x02R\x14lastRecalledAtUnixMs\x88\x01\x01\x128\n" +
	"\x19next_attention_at_unix_ms\x18\x1e \x01(\x04R\x15nextAttentionAtUnixMs\x12\x1e\n" +
	"\bttl_secs\x18\x1f \x01(\x04H\x03R\attlSecs\x88\x01\x01\x12:\n" +
	"\x17protected_until_unix_ms\x18  \x01(\x04H\x04R\x14protectedUntilUnixMs\x88\x01\x01\x125\n" +
	"\x15last_decay_at_unix_ms\x18! \x01(\x04H\x05R\x11lastDecayAtUnixMs\x88\x01\x01\x12B\n" +
	"\x1clast_health_check_at_unix_ms\x18\" \x01(\x04H\x06R\x17lastHealthCheckAtUnixMs\x88\x01\x01B\t\n" +
	"\a_sourceB\x16\n" +
	"\x14_archived_at_unix_msB\x1b\n" +
	"\x19_last_recalled_at_unix_msB\v\n" +
	"\t_ttl_secsB\x1a\n" +
	"\x18_protected_until_unix_msB\x18\n" +
	"\x16_last_decay_at_unix_msB\x1f\n" +
	"\x1d_last_health_check_at_unix_ms\"M\n" +
	"\x06Vector\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\rR\x03dim\x12\x16\n" +
	"\x06values\x18\x03 \x03(\x02R\x06values\"\xe4\x01\n" +
	"\x04Edge\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x02R\bstrength\x12+\n" +
	"\x12created_at_unix_ms\x18\x02 \x01(\x04R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\x03 \x01(\x04R\x0fupdatedAtUnixMs\x12-\n" +
	"\x04meta\x18\x04 \x03(\v2\x19.record.v1.Edge.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*A\n" +
	"\n" +
	"RecordType\x12\x1b\n" +
	"\x17RECORD_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RECORD_TYPE_MEMORY\x10\x01B4Z2github.com/remem-org/remem-go/internal/codec/pb;pbb\x06proto3"

var (
	file_record_v1_record_proto_rawDescOnce sync.Once
	file_record_v1_record_proto_rawDescData []byte
)

func file_record_v1_record_proto_rawDescGZIP() []byte {
	file_record_v1_record_proto_rawDescOnce.Do(func() {
		file_record_v1_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_record_v1_record_proto_rawDesc), len(file_record_v1_record_proto_rawDesc)))
	})
	return file_record_v1_record_proto_rawDescData
}

var file_record_v1_record_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_record_v1_record_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_record_v1_record_proto_goTypes = []any{
	(RecordType)(0), // 0: record.v1.RecordType
	(*Record)(nil),  // 1: record.v1.Record
	(*Vector)(nil),  // 2: record.v1.Vector
	(*Edge)(nil),    // 3: record.v1.Edge
	nil,             // 4: record.v1.Edge.MetaEntry
}
var file_record_v1_record_proto_depIdxs = []int32{
	0, // 0: record.v1.Record.type:type_name -> record.v1.RecordType
	4, // 1: record.v1.Edge.meta:type_name -> record.v1.Edge.MetaEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_record_v1_record_proto_init() }
func file_record_v1_record_proto_init() {
	if File_record_v1_record_proto != nil {
		return
	}
	file_record_v1_record_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_record_v1_record_proto_rawDesc), len(file_record_v1_record_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_v1_record_proto_goTypes,
		DependencyIndexes: file_record_v1_record_proto_depIdxs,
		EnumInfos:         file_record_v1_record_proto_enumTypes,
		MessageInfos:      file_record_v1_record_proto_msgTypes,
	}.Build()
	File_record_v1_record_proto = out.File
	file_record_v1_record_proto_goTypes = nil
	file_record_v1_record_proto_depIdxs = nil
}
