// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: lifecycle/v1/policy.proto

// Package lifecycle.v1 is a tenant's retention policy overrides: the value
// stored at the untenanted system key /policies/<tenant>.
//
// # Why it is not inside the tenant directory row
//
// Plan §Phase 10 Task 1 says "per-tenant overrides stored in tenant metadata",
// and this is that — one row per tenant, in the same untenanted system space as
// the directory row beside it, read the same way. What it is not is a *field on*
// the directory row, and the reason is the dependency direction.
//
// internal/keys imports internal/tenant, so internal/tenant cannot import
// internal/lifecycle. Putting the overrides on tenant.Meta would therefore mean
// either a second copy of the Policy struct in internal/tenant — two
// declarations of one durable shape, which eventually disagree — or moving
// retention semantics into the package whose job is isolation identity. A row
// of its own costs one system prefix and keeps the policy's meaning in the
// package that acts on it.
//
// # An override states a whole policy, not a patch
//
// "No TTL" and "TTL unstated" are different facts, and a partial durable record
// cannot hold them apart. So the patching happens at the API edge, where JSON
// null and JSON absent are distinguishable, and what reaches disk is complete.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Overrides is one tenant's policy table.
//
// The tenant is the key and is deliberately not in the value, the rule every
// other row here follows.
type Overrides struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// policies are the tenant's retention policies, keyed by name. A name that is
	// also a built-in replaces it for this tenant; a name that is not adds one.
	Policies        map[string]*RetentionPolicy `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAtUnixMs uint64                      `protobuf:"varint,2,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Overrides) Reset() {
	*x = Overrides{}
	mi := &file_lifecycle_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overrides) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overrides) ProtoMessage() {}

func (x *Overrides) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overrides.ProtoReflect.Descriptor instead.
func (*Overrides) Descriptor() ([]byte, []int) {
	return file_lifecycle_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *Overrides) GetPolicies() map[string]*RetentionPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *Overrides) GetUpdatedAtUnixMs() uint64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

// RetentionPolicy is one named set of retention rules (plan §II.6).
//
// Every field that can mean "never" is optional, because for each of them
// "never" and "zero" are different things: a cleanup_after of zero would delete
// a memory the instant it was archived, where its absence means the record is
// kept until somebody asks for it to go.
type RetentionPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ttl_secs is the default expiry for memories of this policy. Absent means
	// they never expire on the clock — which is Rust's behaviour for short_term
	// and is not what plan §II.6's table says.
	TtlSecs *uint64 `protobuf:"varint,1,opt,name=ttl_secs,json=ttlSecs,proto3,oneof" json:"ttl_secs,omitempty"`
	// promote_at_recalls and promote_to move an expired memory into another
	// policy instead of archiving it. Absent never promotes.
	PromoteAtRecalls *uint32 `protobuf:"varint,2,opt,name=promote_at_recalls,json=promoteAtRecalls,proto3,oneof" json:"promote_at_recalls,omitempty"`
	PromoteTo        string  `protobuf:"bytes,3,opt,name=promote_to,json=promoteTo,proto3" json:"promote_to,omitempty"`
	// importance_decay is the per-day multiplier; 1.0 is no decay. It is a
	// double rather than a float because it is exponentiated over hundreds of
	// days and the comparison with Rust is to 1e-6.
	ImportanceDecay float64 `protobuf:"fixed64,4,opt,name=importance_decay,json=importanceDecay,proto3" json:"importance_decay,omitempty"`
	// health_decay is points of health lost per whole elapsed day; 0 is none.
	HealthDecay float64 `protobuf:"fixed64,5,opt,name=health_decay,json=healthDecay,proto3" json:"health_decay,omitempty"`
	// archive_at_health is the health at or below which the memory is retired.
	// Absent means health never archives it.
	ArchiveAtHealth *float32 `protobuf:"fixed32,6,opt,name=archive_at_health,json=archiveAtHealth,proto3,oneof" json:"archive_at_health,omitempty"`
	// cleanup_after_secs is how long an archived record is retained before it is
	// removed. Absent means never.
	CleanupAfterSecs *uint64 `protobuf:"varint,7,opt,name=cleanup_after_secs,json=cleanupAfterSecs,proto3,oneof" json:"cleanup_after_secs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetentionPolicy) Reset() {
	*x = RetentionPolicy{}
	mi := &file_lifecycle_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionPolicy) ProtoMessage() {}

func (x *RetentionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionPolicy.ProtoReflect.Descriptor instead.
func (*RetentionPolicy) Descriptor() ([]byte, []int) {
	return file_lifecycle_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *RetentionPolicy) GetTtlSecs() uint64 {
	if x != nil && x.TtlSecs != nil {
		return *x.TtlSecs
	}
	return 0
}

func (x *RetentionPolicy) GetPromoteAtRecalls() uint32 {
	if x != nil && x.PromoteAtRecalls != nil {
		return *x.PromoteAtRecalls
	}
	return 0
}

func (x *RetentionPolicy) GetPromoteTo() string {
	if x != nil {
		return x.PromoteTo
	}
	return ""
}

func (x *RetentionPolicy) GetImportanceDecay() float64 {
	if x != nil {
		return x.ImportanceDecay
	}
	return 0
}

func (x *RetentionPolicy) GetHealthDecay() float64 {
	if x != nil {
		return x.HealthDecay
	}
	return 0
}

func (x *RetentionPolicy) GetArchiveAtHealth() float32 {
	if x != nil && x.ArchiveAtHealth != nil {
		return *x.ArchiveAtHealth
	}
	return 0
}

func (x *RetentionPolicy) GetCleanupAfterSecs() uint64 {
	if x != nil && x.CleanupAfterSecs != nil {
		return *x.CleanupAfterSecs
	}
	return 0
}

var File_lifecycle_v1_policy_proto protoreflect.FileDescriptor

const file_lifecycle_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x19lifecycle/v1/policy.proto\x12\flifecycle.v1\"\xd7\x01\n" +
	"\tOverrides\x12A\n" +
	"\bpolicies\x18\x01 \x03(\v2%.lifecycle.v1.Overrides.PoliciesEntryR\bpolicies\x12+\n" +
	"\x12updated_at_unix_ms\x18\x02 \x01(\x04R\x0fupdatedAtUnixMs\x1aZ\n" +
	"\rPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.lifecycle.v1.RetentionPolicyR\x05value:\x028\x01\"\x86\x03\n" +
	"\x0fRetentionPolicy\x12\x1e\n" +
	"\bttl_secs\x18\x01 \x01(\x04H\x00R\attlSecs\x88\x01\x01\x121\n" +
	"\x12promote_at_recalls\x18\x02 \x01(\rH\x01R\x10promoteAtRecalls\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"promote_to\x18\x03 \x01(\tR\tpromoteTo\x12)\n" +
	"\x10importance_decay\x18\x04 \x01(\x01R\x0fimportanceDecay\x12!\n" +
	"\fhealth_decay\x18\x05 \x01(\x01R\vhealthDecay\x12/\n" +
	"\x11archive_at_health\x18\x06 \x01(\x02H\x02R\x0farchiveAtHealth\x88\x01\x01\x121\n" +
	"\x12cleanup_after_secs\x18\a \x01(\x04H\x03R\x10cleanupAfterSecs\x88\x01\x01B\v\n" +
	"\t_ttl_secsB\x15\n" +
	"\x13_promote_at_recallsB\x14\n" +
	"\x12_archive_at_healthB\x15\n" +
	"\x13_cleanup_after_secsBAZ?github.com/remem-org/remem-go/internal/lifecycle/policykv/pb;pbb\x06proto3"

var (
	file_lifecycle_v1_policy_proto_rawDescOnce sync.Once
	file_lifecycle_v1_policy_proto_rawDescData []byte
)

func file_lifecycle_v1_policy_proto_rawDescGZIP() []byte {
	file_lifecycle_v1_policy_proto_rawDescOnce.Do(func() {
		file_lifecycle_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lifecycle_v1_policy_proto_rawDesc), len(file_lifecycle_v1_policy_proto_rawDesc)))
	})
	return file_lifecycle_v1_policy_proto_rawDescData
}

var file_lifecycle_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lifecycle_v1_policy_proto_goTypes = []any{
	(*Overrides)(nil),       // 0: lifecycle.v1.Overrides
	(*RetentionPolicy)(nil), // 1: lifecycle.v1.RetentionPolicy
	nil,                     // 2: lifecycle.v1.Overrides.PoliciesEntry
}
var file_lifecycle_v1_policy_proto_depIdxs = []int32{
	2, // 0: lifecycle.v1.Overrides.policies:type_name -> lifecycle.v1.Overrides.PoliciesEntry
	1, // 1: lifecycle.v1.Overrides.PoliciesEntry.value:type_name -> lifecycle.v1.RetentionPolicy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lifecycle_v1_policy_proto_init() }
func file_lifecycle_v1_policy_proto_init() {
	if File_lifecycle_v1_policy_proto != nil {
		return
	}
	file_lifecycle_v1_policy_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lifecycle_v1_policy_proto_rawDesc), len(file_lifecycle_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lifecycle_v1_policy_proto_goTypes,
		DependencyIndexes: file_lifecycle_v1_policy_proto_depIdxs,
		MessageInfos:      file_lifecycle_v1_policy_proto_msgTypes,
	}.Build()
	File_lifecycle_v1_policy_proto = out.File
	file_lifecycle_v1_policy_proto_goTypes = nil
	file_lifecycle_v1_policy_proto_depIdxs = nil
}
