// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: job/v1/job.proto

// Package job.v1 is the durable job row: the value stored in the job key space.
//
// Job state is canonical (plan §II.4). Nothing reconstructs it, and a lost row
// is lost work — which is the specific Rust defect this framework replaces, a
// bounded channel that dropped discovery work under load and counted the drops.
// There is no rebuild path for this space and there must not be one.
//
// It is not a fifth independently versioned durable format. Protobuf's
// field-number evolution carries it forward, which is the same footing the
// tenant directory and the session registry are on.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job is one unit of background work.
//
// The tenant and the job id are deliberately absent: both are in the key, and a
// second copy inside the value is a second thing that can disagree with the
// first. The key also carries the *partition* — pending, running or done — so
// the state below is the finer logical state within it, and the two are kept in
// step by writing both halves of every transition in one transaction.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type names the registered handler. It is a durable name: it is written
	// into every row of that type, and a retired one stays retired.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// payload is opaque to the framework and meaningful only to the handler.
	// It is a reference to work, not the work, and is bounded accordingly.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// state is the logical state: pending, running, retry, completed, failed or
	// cancelled.
	State uint32 `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	// attempts counts runs, not retries. max_attempts is the bound it is
	// compared against; a job that reaches it is failed with last_error kept.
	Attempts    uint32 `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts uint32 `protobuf:"varint,5,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// run_at_unix_ms is when the job becomes claimable. It is the due time
	// encoded in a pending key, and it moves forward on every retry.
	RunAtUnixMs uint64 `protobuf:"varint,6,opt,name=run_at_unix_ms,json=runAtUnixMs,proto3" json:"run_at_unix_ms,omitempty"`
	// lease is present exactly while the job is running.
	Lease *Lease `protobuf:"bytes,7,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	// checkpoint is the handler's own progress cursor, opaque here. It survives
	// reclamation and restart, which is what makes a long job restartable
	// without redoing the half it finished.
	Checkpoint []byte `protobuf:"bytes,8,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	// last_error is the message from the most recent failure, kept so that a
	// failed job says why without an operator reading the logs.
	LastError string `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// priority orders the jobs within one claim batch and nothing wider: the key
	// is ordered by due time and priority is not in it.
	Priority        int32  `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAtUnixMs uint64 `protobuf:"varint,11,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs uint64 `protobuf:"varint,12,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	// namespace is the subdivision within the tenant the job acts on. It is in
	// the key as well, and is stored here because a job's *subject* namespace is
	// what a handler needs and the key's is where the row happens to live —
	// today they are always the same value and the day they are not, the handler
	// must read the one it was given.
	Namespace     string `protobuf:"bytes,13,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_job_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Job) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Job) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Job) GetRunAtUnixMs() uint64 {
	if x != nil {
		return x.RunAtUnixMs
	}
	return 0
}

func (x *Job) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *Job) GetCheckpoint() []byte {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *Job) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Job) GetUpdatedAtUnixMs() uint64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *Job) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// Lease is one worker's claim on a running job.
//
// Owner and token exist from the first commit even though there is one node.
// That is spec §24's "abstractions compatible with future distributed
// execution": cross-node claiming becomes a change to how a lease is granted,
// never a change to a handler, and retrofitting fencing later would mean
// auditing every handler there is.
type Lease struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// owner is the node id that holds the lease.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// expires_at_unix_ms is when the claim lapses and the job may be reclaimed.
	// It is also the due time encoded in a running key, so reclaiming lapsed
	// leases is the same bounded forward scan that claiming due work is.
	ExpiresAtUnixMs uint64 `protobuf:"varint,2,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	// token fences a reclaimed job against its previous owner. Reclamation draws
	// a new one, so a worker that wakes up holding the old one is refused rather
	// than allowed to complete work somebody else has since redone.
	Token         []byte `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_job_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *Lease) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Lease) GetExpiresAtUnixMs() uint64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *Lease) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// Pause is an operator's suppression of one recurring type's scheduling in one
// tenant.
//
// The type it suppresses is in the key as well as here for the reason the job
// row's namespace is: the key is where the row lives, and this is what the
// record says about itself. A pause is not a boolean, because a suppression
// with no expiry outlives the memory of setting it — and what these jobs do is
// repair.
type Pause struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type names the registered recurring type whose scheduled enqueueing is
	// suppressed. Manual runs are unaffected.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// expires_at_unix_ms is when the suppression lifts. It is required and
	// bounded: the scheduler compares it against its own clock, so a crash or a
	// missed cleanup cannot leave a pause in force indefinitely.
	ExpiresAtUnixMs uint64 `protobuf:"varint,2,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	// set_by is the operator credential that asked for the pause, so that the
	// status surface can say who suppressed the work rather than only that
	// somebody did.
	SetBy         string `protobuf:"bytes,3,opt,name=set_by,json=setBy,proto3" json:"set_by,omitempty"`
	SetAtUnixMs   uint64 `protobuf:"varint,4,opt,name=set_at_unix_ms,json=setAtUnixMs,proto3" json:"set_at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pause) Reset() {
	*x = Pause{}
	mi := &file_job_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pause) ProtoMessage() {}

func (x *Pause) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pause.ProtoReflect.Descriptor instead.
func (*Pause) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *Pause) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Pause) GetExpiresAtUnixMs() uint64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *Pause) GetSetBy() string {
	if x != nil {
		return x.SetBy
	}
	return ""
}

func (x *Pause) GetSetAtUnixMs() uint64 {
	if x != nil {
		return x.SetAtUnixMs
	}
	return 0
}

// Run is one execution attempt, retained for jobs.retention.
//
// It describes one attempt and not a deduplicated total across retries:
// delivery is at-least-once, so the same record can be visited more than once
// and a sum across attempts is not a count of distinct records.
type Run struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the job this attempt belongs to. Several runs share one.
	JobId []byte `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// type names the registered handler, copied here because history is read by
	// type and the job row it came from may already have been reaped.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// attempt is the run number the queue charged, counting from one.
	Attempt          uint32 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StartedAtUnixMs  uint64 `protobuf:"varint,4,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	FinishedAtUnixMs uint64 `protobuf:"varint,5,opt,name=finished_at_unix_ms,json=finishedAtUnixMs,proto3" json:"finished_at_unix_ms,omitempty"`
	// outcome is the logical state the attempt ended in: completed, retry,
	// failed or cancelled.
	Outcome uint32 `protobuf:"varint,6,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// error is the failure message, empty on success.
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// records_processed and records_changed are what the handler reported for
	// this attempt, and are absent when it reported nothing. Absent is not zero:
	// "this attempt changed nothing" and "nobody counted" are different answers,
	// and neither may be inferred from a checkpoint, an elapsed time or the size
	// of an index afterwards.
	RecordsProcessed *uint64 `protobuf:"varint,8,opt,name=records_processed,json=recordsProcessed,proto3,oneof" json:"records_processed,omitempty"`
	RecordsChanged   *uint64 `protobuf:"varint,9,opt,name=records_changed,json=recordsChanged,proto3,oneof" json:"records_changed,omitempty"`
	// owner is the node that ran the attempt.
	Owner string `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	// namespace is the subdivision the attempt acted on.
	Namespace     string `protobuf:"bytes,11,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_job_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *Run) GetJobId() []byte {
	if x != nil {
		return x.JobId
	}
	return nil
}

func (x *Run) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Run) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Run) GetStartedAtUnixMs() uint64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *Run) GetFinishedAtUnixMs() uint64 {
	if x != nil {
		return x.FinishedAtUnixMs
	}
	return 0
}

func (x *Run) GetOutcome() uint32 {
	if x != nil {
		return x.Outcome
	}
	return 0
}

func (x *Run) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Run) GetRecordsProcessed() uint64 {
	if x != nil && x.RecordsProcessed != nil {
		return *x.RecordsProcessed
	}
	return 0
}

func (x *Run) GetRecordsChanged() uint64 {
	if x != nil && x.RecordsChanged != nil {
		return *x.RecordsChanged
	}
	return 0
}

func (x *Run) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Run) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_job_v1_job_proto protoreflect.FileDescriptor

const file_job_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x10job/v1/job.proto\x12\x06job.v1\"\xb4\x03\n" +
	"\x03Job\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05state\x18\x03 \x01(\rR\x05state\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\rR\battempts\x12!\n" +
	"\fmax_attempts\x18\x05 \x01(\rR\vmaxAttempts\x12#\n" +
	"\x0erun_at_unix_ms\x18\x06 \x01(\x04R\vrunAtUnixMs\x12(\n" +
	"\x05lease\x18\a \x01(\v2\r.job.v1.LeaseH\x00R\x05lease\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\b \x01(\fR\n" +
	"checkpoint\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12+\n" +
	"\x12created_at_unix_ms\x18\v \x01(\x04R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\f \x01(\x04R\x0fupdatedAtUnixMs\x12\x1c\n" +
	"\tnamespace\x18\r \x01(\tR\tnamespaceB\b\n" +
	"\x06_lease\"`\n" +
	"\x05Lease\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12+\n" +
	"\x12expires_at_unix_ms\x18\x02 \x01(\x04R\x0fexpiresAtUnixMs\x12\x14\n" +
	"\x05token\x18\x03 \x01(\fR\x05token\"\x84\x01\n" +
	"\x05Pause\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12+\n" +
	"\x12expires_at_unix_ms\x18\x02 \x01(\x04R\x0fexpiresAtUnixMs\x12\x15\n" +
	"\x06set_by\x18\x03 \x01(\tR\x05setBy\x12#\n" +
	"\x0eset_at_unix_ms\x18\x04 \x01(\x04R\vsetAtUnixMs\"\x94\x03\n" +
	"\x03Run\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\fR\x05jobId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\x12+\n" +
	"\x12started_at_unix_ms\x18\x04 \x01(\x04R\x0fstartedAtUnixMs\x12-\n" +
	"\x13finished_at_unix_ms\x18\x05 \x01(\x04R\x10finishedAtUnixMs\x12\x18\n" +
	"\aoutcome\x18\x06 \x01(\rR\aoutcome\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x120\n" +
	"\x11records_processed\x18\b \x01(\x04H\x00R\x10recordsProcessed\x88\x01\x01\x12,\n" +
	"\x0frecords_changed\x18\t \x01(\x04H\x01R\x0erecordsChanged\x88\x01\x01\x12\x14\n" +
	"\x05owner\x18\n" +
	" \x01(\tR\x05owner\x12\x1c\n" +
	"\tnamespace\x18\v \x01(\tR\tnamespaceB\x14\n" +
	"\x12_records_processedB\x12\n" +
	"\x10_records_changedB3Z1github.com/remem-org/remem-go/internal/jobs/pb;pbb\x06proto3"

var (
	file_job_v1_job_proto_rawDescOnce sync.Once
	file_job_v1_job_proto_rawDescData []byte
)

func file_job_v1_job_proto_rawDescGZIP() []byte {
	file_job_v1_job_proto_rawDescOnce.Do(func() {
		file_job_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_v1_job_proto_rawDesc), len(file_job_v1_job_proto_rawDesc)))
	})
	return file_job_v1_job_proto_rawDescData
}

var file_job_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_job_v1_job_proto_goTypes = []any{
	(*Job)(nil),   // 0: job.v1.Job
	(*Lease)(nil), // 1: job.v1.Lease
	(*Pause)(nil), // 2: job.v1.Pause
	(*Run)(nil),   // 3: job.v1.Run
}
var file_job_v1_job_proto_depIdxs = []int32{
	1, // 0: job.v1.Job.lease:type_name -> job.v1.Lease
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_job_v1_job_proto_init() }
func file_job_v1_job_proto_init() {
	if File_job_v1_job_proto != nil {
		return
	}
	file_job_v1_job_proto_msgTypes[0].OneofWrappers = []any{}
	file_job_v1_job_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_v1_job_proto_rawDesc), len(file_job_v1_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_job_v1_job_proto_goTypes,
		DependencyIndexes: file_job_v1_job_proto_depIdxs,
		MessageInfos:      file_job_v1_job_proto_msgTypes,
	}.Build()
	File_job_v1_job_proto = out.File
	file_job_v1_job_proto_goTypes = nil
	file_job_v1_job_proto_depIdxs = nil
}
