// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: snapshot/v1/snapshot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CreatedAtUnixMs     uint64                 `protobuf:"varint,1,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	SourceImpl          string                 `protobuf:"bytes,2,opt,name=source_impl,json=sourceImpl,proto3" json:"source_impl,omitempty"` // "rust" | "go"
	SourceVersion       string                 `protobuf:"bytes,3,opt,name=source_version,json=sourceVersion,proto3" json:"source_version,omitempty"`
	RecordFormatVersion uint32                 `protobuf:"varint,4,opt,name=record_format_version,json=recordFormatVersion,proto3" json:"record_format_version,omitempty"`
	Tenants             []string               `protobuf:"bytes,5,rep,name=tenants,proto3" json:"tenants,omitempty"`
	RecordCount         uint64                 `protobuf:"varint,6,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	VectorCount         uint64                 `protobuf:"varint,7,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	EdgeCount           uint64                 `protobuf:"varint,8,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	EventCount          uint64                 `protobuf:"varint,9,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Header) GetSourceImpl() string {
	if x != nil {
		return x.SourceImpl
	}
	return ""
}

func (x *Header) GetSourceVersion() string {
	if x != nil {
		return x.SourceVersion
	}
	return ""
}

func (x *Header) GetRecordFormatVersion() uint32 {
	if x != nil {
		return x.RecordFormatVersion
	}
	return 0
}

func (x *Header) GetTenants() []string {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *Header) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *Header) GetVectorCount() uint64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *Header) GetEdgeCount() uint64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *Header) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

type Tenant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CreatedAtUnixMs uint64                 `protobuf:"varint,3,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Tenant) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type Record struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Tenant                  string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Id                      []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // 16-byte UUID
	Content                 string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Policy                  string                 `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"` // "short_term" | "long_term" | "pinned"
	Archived                bool                   `protobuf:"varint,5,opt,name=archived,proto3" json:"archived,omitempty"`
	CreatedAtUnixMs         uint64                 `protobuf:"varint,6,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs         uint64                 `protobuf:"varint,7,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	AccessedAtUnixMs        uint64                 `protobuf:"varint,8,opt,name=accessed_at_unix_ms,json=accessedAtUnixMs,proto3" json:"accessed_at_unix_ms,omitempty"`
	AccessCount             uint32                 `protobuf:"varint,9,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	Source                  *string                `protobuf:"bytes,10,opt,name=source,proto3,oneof" json:"source,omitempty"`
	Tags                    []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	Importance              float32                `protobuf:"fixed32,12,opt,name=importance,proto3" json:"importance,omitempty"`
	EmotionalValence        float32                `protobuf:"fixed32,13,opt,name=emotional_valence,json=emotionalValence,proto3" json:"emotional_valence,omitempty"`
	Arousal                 float32                `protobuf:"fixed32,14,opt,name=arousal,proto3" json:"arousal,omitempty"`
	Health                  float32                `protobuf:"fixed32,15,opt,name=health,proto3" json:"health,omitempty"`
	LastRecalledAtUnixMs    *uint64                `protobuf:"varint,16,opt,name=last_recalled_at_unix_ms,json=lastRecalledAtUnixMs,proto3,oneof" json:"last_recalled_at_unix_ms,omitempty"`
	FlashbulbUntilUnixMs    *uint64                `protobuf:"varint,17,opt,name=flashbulb_until_unix_ms,json=flashbulbUntilUnixMs,proto3,oneof" json:"flashbulb_until_unix_ms,omitempty"`
	TtlSeconds              *uint64                `protobuf:"varint,18,opt,name=ttl_seconds,json=ttlSeconds,proto3,oneof" json:"ttl_seconds,omitempty"`
	LastDecayAtUnixMs       *uint64                `protobuf:"varint,19,opt,name=last_decay_at_unix_ms,json=lastDecayAtUnixMs,proto3,oneof" json:"last_decay_at_unix_ms,omitempty"`
	LastHealthCheckAtUnixMs *uint64                `protobuf:"varint,20,opt,name=last_health_check_at_unix_ms,json=lastHealthCheckAtUnixMs,proto3,oneof" json:"last_health_check_at_unix_ms,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *Record) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Record) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Record) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Record) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *Record) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Record) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Record) GetUpdatedAtUnixMs() uint64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *Record) GetAccessedAtUnixMs() uint64 {
	if x != nil {
		return x.AccessedAtUnixMs
	}
	return 0
}

func (x *Record) GetAccessCount() uint32 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

func (x *Record) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Record) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Record) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Record) GetEmotionalValence() float32 {
	if x != nil {
		return x.EmotionalValence
	}
	return 0
}

func (x *Record) GetArousal() float32 {
	if x != nil {
		return x.Arousal
	}
	return 0
}

func (x *Record) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Record) GetLastRecalledAtUnixMs() uint64 {
	if x != nil && x.LastRecalledAtUnixMs != nil {
		return *x.LastRecalledAtUnixMs
	}
	return 0
}

func (x *Record) GetFlashbulbUntilUnixMs() uint64 {
	if x != nil && x.FlashbulbUntilUnixMs != nil {
		return *x.FlashbulbUntilUnixMs
	}
	return 0
}

func (x *Record) GetTtlSeconds() uint64 {
	if x != nil && x.TtlSeconds != nil {
		return *x.TtlSeconds
	}
	return 0
}

func (x *Record) GetLastDecayAtUnixMs() uint64 {
	if x != nil && x.LastDecayAtUnixMs != nil {
		return *x.LastDecayAtUnixMs
	}
	return 0
}

func (x *Record) GetLastHealthCheckAtUnixMs() uint64 {
	if x != nil && x.LastHealthCheckAtUnixMs != nil {
		return *x.LastHealthCheckAtUnixMs
	}
	return 0
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // "all-MiniLM-L6-v2"
	Dim           uint32                 `protobuf:"varint,4,opt,name=dim,proto3" json:"dim,omitempty"`
	Values        []float32              `protobuf:"fixed32,5,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *Vector) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Vector) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Vector) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *Vector) GetDim() uint32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Edge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tenant           string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	From             []byte                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To               []byte                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	RelationshipType string                 `protobuf:"bytes,4,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	Strength         float32                `protobuf:"fixed32,5,opt,name=strength,proto3" json:"strength,omitempty"`
	CreatedAtUnixMs  uint64                 `protobuf:"varint,6,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *Edge) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Edge) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Edge) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Edge) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *Edge) GetStrength() float32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Edge) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Subject       []byte                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	AtUnixMs      uint64                 `protobuf:"varint,3,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // "recalled" | "archived" | "promoted" | "decayed"
	Detail        string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Event) GetSubject() []byte {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Event) GetAtUnixMs() uint64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_snapshot_v1_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1asnapshot/v1/snapshot.proto\x12\vsnapshot.v1\"\xd1\x02\n" +
	"\x06Header\x12+\n" +
	"\x12created_at_unix_ms\x18\x01 \x01(\x04R\x0fcreatedAtUnixMs\x12\x1f\n" +
	"\vsource_impl\x18\x02 \x01(\tR\n" +
	"sourceImpl\x12%\n" +
	"\x0esource_version\x18\x03 \x01(\tR\rsourceVersion\x122\n" +
	"\x15record_format_version\x18\x04 \x01(\rR\x13recordFormatVersion\x12\x18\n" +
	"\atenants\x18\x05 \x03(\tR\atenants\x12!\n" +
	"\frecord_count\x18\x06 \x01(\x04R\vrecordCount\x12!\n" +
	"\fvector_count\x18\a \x01(\x04R\vvectorCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\b \x01(\x04R\tedgeCount\x12\x1f\n" +
	"\vevent_count\x18\t \x01(\x04R\n" +
	"eventCount\"h\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12+\n" +
	"\x12created_at_unix_ms\x18\x03 \x01(\x04R\x0fcreatedAtUnixMs\"\x83\a\n" +
	"\x06Record\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06policy\x18\x04 \x01(\tR\x06policy\x12\x1a\n" +
	"\barchived\x18\x05 \x01(\bR\barchived\x12+\n" +
	"\x12created_at_unix_ms\x18\x06 \x01(\x04R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\a \x01(\x04R\x0fupdatedAtUnixMs\x12-\n" +
	"\x13accessed_at_unix_ms\x18\b \x01(\x04R\x10accessedAtUnixMs\x12!\n" +
	"\faccess_count\x18\t \x01(\rR\vaccessCount\x12\x1b\n" +
	"\x06source\x18\n" +
	" \x01(\tH\x00R\x06source\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"importance\x18\f \x01(\x02R\n" +
	"importance\x12+\n" +
	"\x11emotional_valence\x18\r \x01(\x02R\x10emotionalValence\x12\x18\n" +
	"\aarousal\x18\x0e \x01(\x02R\aarousal\x12\x16\n" +
	"\x06health\x18\x0f \x01(\x02R\x06health\x12;\n" +
	"\x18last_recalled_at_unix_ms\x18\x10 \x01(\x04H\x01R\x14lastRecalledAtUnixMs\x88\x01\x01\x12:\n" +
	"\x17flashbulb_until_unix_ms\x18\x11 \x01(\x04H\x02R\x14flashbulbUntilUnixMs\x88\x01\x01\x12$\n" +
	"\vttl_seconds\x18\x12 \x01(\x04H\x03R\n" +
	"ttlSeconds\x88\x01\x01\x125\n" +
	"\x15last_decay_at_unix_ms\x18\x13 \x01(\x04H\x04R\x11lastDecayAtUnixMs\x88\x01\x01\x12B\n" +
	"\x1clast_health_check_at_unix_ms\x18\x14 \x01(\x04H\x05R\x17lastHealthCheckAtUnixMs\x88\x01\x01B\t\n" +
	"\a_sourceB\x1b\n" +
	"\x19_last_recalled_at_unix_msB\x1a\n" +
	"\x18_flashbulb_until_unix_msB\x0e\n" +
	"\f_ttl_secondsB\x18\n" +
	"\x16_last_decay_at_unix_msB\x1f\n" +
	"\x1d_last_health_check_at_unix_ms\"y\n" +
	"\x06Vector\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x10\n" +
	"\x03dim\x18\x04 \x01(\rR\x03dim\x12\x1a\n" +
	"\x06values\x18\x05 \x03(\x02B\x02\x10\x01R\x06values\"\xb8\x01\n" +
	"\x04Edge\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04from\x18\x02 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\fR\x02to\x12+\n" +
	"\x11relationship_type\x18\x04 \x01(\tR\x10relationshipType\x12\x1a\n" +
	"\bstrength\x18\x05 \x01(\x02R\bstrength\x12+\n" +
	"\x12created_at_unix_ms\x18\x06 \x01(\x04R\x0fcreatedAtUnixMs\"\x83\x01\n" +
	"\x05Event\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x18\n" +
	"\asubject\x18\x02 \x01(\fR\asubject\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x03 \x01(\x04R\batUnixMs\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detailB\xa1\x01\n" +
	"\x0fcom.snapshot.v1B\rSnapshotProtoP\x01Z2github.com/remem-org/remem-go/internal/snapshot/pb\xa2\x02\x03SXX\xaa\x02\vSnapshot.V1\xca\x02\vSnapshot\\V1\xe2\x02\x17Snapshot\\V1\\GPBMetadata\xea\x02\fSnapshot::V1b\x06proto3"

var (
	file_snapshot_v1_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_v1_snapshot_proto_rawDescData []byte
)

func file_snapshot_v1_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_v1_snapshot_proto_rawDesc), len(file_snapshot_v1_snapshot_proto_rawDesc)))
	})
	return file_snapshot_v1_snapshot_proto_rawDescData
}

var file_snapshot_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_snapshot_v1_snapshot_proto_goTypes = []any{
	(*Header)(nil), // 0: snapshot.v1.Header
	(*Tenant)(nil), // 1: snapshot.v1.Tenant
	(*Record)(nil), // 2: snapshot.v1.Record
	(*Vector)(nil), // 3: snapshot.v1.Vector
	(*Edge)(nil),   // 4: snapshot.v1.Edge
	(*Event)(nil),  // 5: snapshot.v1.Event
}
var file_snapshot_v1_snapshot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snapshot_v1_snapshot_proto_init() }
func file_snapshot_v1_snapshot_proto_init() {
	if File_snapshot_v1_snapshot_proto != nil {
		return
	}
	file_snapshot_v1_snapshot_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_v1_snapshot_proto_rawDesc), len(file_snapshot_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_snapshot_v1_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_v1_snapshot_proto = out.File
	file_snapshot_v1_snapshot_proto_goTypes = nil
	file_snapshot_v1_snapshot_proto_depIdxs = nil
}
