// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: snapshotext/v1/snapshot_ext.proto

// Go-native companion sections for the portable snapshot.
//
// proto/snapshot/v1/snapshot.proto is the migration contract: byte-shared with
// the frozen Rust implementation, checksummed in both repositories, and
// therefore fixed. It predates Go's graph (Phase 6) and lifecycle (Phase 10),
// so there are five things Go stores that it cannot express — connection
// metadata, an edge's update time, a record's archive time, the per-tenant
// schema version, and the lifecycle audit stream in the shape Go actually keeps
// it.
//
// Dropping them would make Remem's only backup format lossy, and Invariant 12
// calls that format the escape route from Pebble. So Go writes the shared
// sections exactly as Rust would, and writes these alongside them: strip the
// companion sections from a Go snapshot and what remains is precisely a
// snapshot.v1 file.
//
// Every message here is keyed the same way as the shared message it annotates,
// and a companion block always immediately follows the block it annotates.

package pbext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecordExt carries what snapshot.v1.Record has no field for.
//
// next_attention_at is deliberately absent: it is derived from the policy and
// the record, and an import recomputes it through the lifecycle scheduler
// rather than trusting a number written by a possibly-differently-configured
// deployment.
type RecordExt struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tenant           string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Id               []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                          // 16-byte UUID, matching Record.id
	ArchivedAtUnixMs uint64                 `protobuf:"varint,3,opt,name=archived_at_unix_ms,json=archivedAtUnixMs,proto3" json:"archived_at_unix_ms,omitempty"` // 0 when the record is not archived
	SchemaVersion    uint32                 `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`              // the tenant user-schema version (spec §19.3)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordExt) Reset() {
	*x = RecordExt{}
	mi := &file_snapshotext_v1_snapshot_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordExt) ProtoMessage() {}

func (x *RecordExt) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotext_v1_snapshot_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordExt.ProtoReflect.Descriptor instead.
func (*RecordExt) Descriptor() ([]byte, []int) {
	return file_snapshotext_v1_snapshot_ext_proto_rawDescGZIP(), []int{0}
}

func (x *RecordExt) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RecordExt) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RecordExt) GetArchivedAtUnixMs() uint64 {
	if x != nil {
		return x.ArchivedAtUnixMs
	}
	return 0
}

func (x *RecordExt) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

// EdgeExt carries what snapshot.v1.Edge has no field for. It is keyed by the
// whole edge identity, because two records may be connected several ways.
type EdgeExt struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tenant           string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	From             []byte                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To               []byte                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	RelationshipType string                 `protobuf:"bytes,4,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	UpdatedAtUnixMs  uint64                 `protobuf:"varint,5,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	Meta             map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // caller-supplied; Remem never interprets it
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EdgeExt) Reset() {
	*x = EdgeExt{}
	mi := &file_snapshotext_v1_snapshot_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeExt) ProtoMessage() {}

func (x *EdgeExt) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotext_v1_snapshot_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeExt.ProtoReflect.Descriptor instead.
func (*EdgeExt) Descriptor() ([]byte, []int) {
	return file_snapshotext_v1_snapshot_ext_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeExt) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *EdgeExt) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EdgeExt) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EdgeExt) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *EdgeExt) GetUpdatedAtUnixMs() uint64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *EdgeExt) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// TenantExt carries what snapshot.v1.Tenant has no field for.
type TenantExt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SchemaVersion uint32                 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantExt) Reset() {
	*x = TenantExt{}
	mi := &file_snapshotext_v1_snapshot_ext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantExt) ProtoMessage() {}

func (x *TenantExt) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotext_v1_snapshot_ext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantExt.ProtoReflect.Descriptor instead.
func (*TenantExt) Descriptor() ([]byte, []int) {
	return file_snapshotext_v1_snapshot_ext_proto_rawDescGZIP(), []int{2}
}

func (x *TenantExt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantExt) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

// Event is one row of the lifecycle audit stream (plan §II.10 row 14).
//
// snapshot.v1.Event exists and is never written by either implementation: it
// flattens an event into a kind and a free-text detail, where Go's is a
// structured record of what moved and why. The audit stream answers "why did my
// memory disappear", including for a memory that has been hard-deleted, so a
// backup that omitted it would lose the one row that outlives its subject.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Subject       []byte                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	AtUnixMs      uint64                 `protobuf:"varint,3,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	Seq           uint32                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"` // breaks ties within a millisecond
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Actor         string                 `protobuf:"bytes,6,opt,name=actor,proto3" json:"actor,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Before        map[string]string      `protobuf:"bytes,8,rep,name=before,proto3" json:"before,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // fields that moved. Never content.
	After         map[string]string      `protobuf:"bytes,9,rep,name=after,proto3" json:"after,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_snapshotext_v1_snapshot_ext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotext_v1_snapshot_ext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_snapshotext_v1_snapshot_ext_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Event) GetSubject() []byte {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Event) GetAtUnixMs() uint64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

func (x *Event) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Event) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Event) GetBefore() map[string]string {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *Event) GetAfter() map[string]string {
	if x != nil {
		return x.After
	}
	return nil
}

var File_snapshotext_v1_snapshot_ext_proto protoreflect.FileDescriptor

const file_snapshotext_v1_snapshot_ext_proto_rawDesc = "" +
	"\n" +
	"!snapshotext/v1/snapshot_ext.proto\x12\x0esnapshotext.v1\"\x89\x01\n" +
	"\tRecordExt\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12-\n" +
	"\x13archived_at_unix_ms\x18\x03 \x01(\x04R\x10archivedAtUnixMs\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\rR\rschemaVersion\"\x8f\x02\n" +
	"\aEdgeExt\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04from\x18\x02 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\fR\x02to\x12+\n" +
	"\x11relationship_type\x18\x04 \x01(\tR\x10relationshipType\x12+\n" +
	"\x12updated_at_unix_ms\x18\x05 \x01(\x04R\x0fupdatedAtUnixMs\x125\n" +
	"\x04meta\x18\x06 \x03(\v2!.snapshotext.v1.EdgeExt.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\tTenantExt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\"\x93\x03\n" +
	"\x05Event\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x18\n" +
	"\asubject\x18\x02 \x01(\fR\asubject\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x03 \x01(\x04R\batUnixMs\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\rR\x03seq\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x14\n" +
	"\x05actor\x18\x06 \x01(\tR\x05actor\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x129\n" +
	"\x06before\x18\b \x03(\v2!.snapshotext.v1.Event.BeforeEntryR\x06before\x126\n" +
	"\x05after\x18\t \x03(\v2 .snapshotext.v1.Event.AfterEntryR\x05after\x1a9\n" +
	"\vBeforeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"AfterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B7Z5github.com/remem-org/remem-go/internal/snapshot/pbextb\x06proto3"

var (
	file_snapshotext_v1_snapshot_ext_proto_rawDescOnce sync.Once
	file_snapshotext_v1_snapshot_ext_proto_rawDescData []byte
)

func file_snapshotext_v1_snapshot_ext_proto_rawDescGZIP() []byte {
	file_snapshotext_v1_snapshot_ext_proto_rawDescOnce.Do(func() {
		file_snapshotext_v1_snapshot_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshotext_v1_snapshot_ext_proto_rawDesc), len(file_snapshotext_v1_snapshot_ext_proto_rawDesc)))
	})
	return file_snapshotext_v1_snapshot_ext_proto_rawDescData
}

var file_snapshotext_v1_snapshot_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_snapshotext_v1_snapshot_ext_proto_goTypes = []any{
	(*RecordExt)(nil), // 0: snapshotext.v1.RecordExt
	(*EdgeExt)(nil),   // 1: snapshotext.v1.EdgeExt
	(*TenantExt)(nil), // 2: snapshotext.v1.TenantExt
	(*Event)(nil),     // 3: snapshotext.v1.Event
	nil,               // 4: snapshotext.v1.EdgeExt.MetaEntry
	nil,               // 5: snapshotext.v1.Event.BeforeEntry
	nil,               // 6: snapshotext.v1.Event.AfterEntry
}
var file_snapshotext_v1_snapshot_ext_proto_depIdxs = []int32{
	4, // 0: snapshotext.v1.EdgeExt.meta:type_name -> snapshotext.v1.EdgeExt.MetaEntry
	5, // 1: snapshotext.v1.Event.before:type_name -> snapshotext.v1.Event.BeforeEntry
	6, // 2: snapshotext.v1.Event.after:type_name -> snapshotext.v1.Event.AfterEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_snapshotext_v1_snapshot_ext_proto_init() }
func file_snapshotext_v1_snapshot_ext_proto_init() {
	if File_snapshotext_v1_snapshot_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshotext_v1_snapshot_ext_proto_rawDesc), len(file_snapshotext_v1_snapshot_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshotext_v1_snapshot_ext_proto_goTypes,
		DependencyIndexes: file_snapshotext_v1_snapshot_ext_proto_depIdxs,
		MessageInfos:      file_snapshotext_v1_snapshot_ext_proto_msgTypes,
	}.Build()
	File_snapshotext_v1_snapshot_ext_proto = out.File
	file_snapshotext_v1_snapshot_ext_proto_goTypes = nil
	file_snapshotext_v1_snapshot_ext_proto_depIdxs = nil
}
