// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: event/v1/event.proto

// Package event.v1 is the durable lifecycle audit record: the value stored in
// the event key space.
//
// The event stream is canonical (plan §II.4). Nothing rebuilds it — an event is
// the record of something that happened, and a lost one is a lost fact about
// the past. It is exported (snapshot section 6) and never reconstructed.
//
// It is not a fifth independently versioned durable format. Protobuf's
// field-number evolution carries it forward, which is the footing the job row,
// the tenant directory and the session registry are already on.
//
// # Content never appears here
//
// The rule that keeps memory content out of logs extends to this stream, and a
// test enforces it. An audit trail is read by operators, shipped to a log
// aggregator and kept long after the memory it describes has been deleted;
// content inside it would outlive every deletion the product offers.
//
// Field number ranges, so later phases do not collide:
//   1-19   identity, kind and provenance
//   20-39  the field deltas
//   40+    later

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event is one thing that happened to one record.
//
// The tenant, the namespace, the subject, the timestamp and the sequence
// number are all in the key, and a second copy inside the value is a second
// thing that can disagree with the first — the rule Record follows for tenant
// and namespace, and Job for its id and partition.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the durable name of the transition: "recalled", "promoted",
	// "expired", "archived", "restored", "hard_deleted". A retired kind stays
	// retired, and a name is never reused for a different meaning.
	//
	// A string rather than an enum because this value is read by operators and
	// by tools outside this binary, and an enum's unknown-variant behaviour —
	// decoding a kind a newer writer introduced as zero — would render a
	// transition nobody can name as one everybody misreads.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// actor is what caused it: "ttl", "active_forgetting", "cleanup", "api".
	// It is the answer to "what did this to my memory", which is the first
	// question anybody asks of an audit trail.
	Actor string `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	// reason is the human sentence: "health reached 0", "ttl elapsed, 5 recalls".
	// It is written for a person reading one row, not parsed by anything.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// before and after are the fields that moved, rendered as short strings.
	// They are maps for the reason Edge.meta is, and they are marshalled
	// deterministically for the same reason: a row's bytes must be a function of
	// the event and nothing else, or two nodes handed the same transition write
	// different rows (Invariants 8 and 9). See internal/events/codec.go.
	//
	// Memory content is never a value here. See the package comment.
	Before        map[string]string `protobuf:"bytes,20,rep,name=before,proto3" json:"before,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	After         map[string]string `protobuf:"bytes,21,rep,name=after,proto3" json:"after,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Event) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Event) GetBefore() map[string]string {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *Event) GetAfter() map[string]string {
	if x != nil {
		return x.After
	}
	return nil
}

var File_event_v1_event_proto protoreflect.FileDescriptor

const file_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x14event/v1/event.proto\x12\bevent.v1\"\xa5\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x123\n" +
	"\x06before\x18\x14 \x03(\v2\x1b.event.v1.Event.BeforeEntryR\x06before\x120\n" +
	"\x05after\x18\x15 \x03(\v2\x1a.event.v1.Event.AfterEntryR\x05after\x1a9\n" +
	"\vBeforeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"AfterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B5Z3github.com/remem-org/remem-go/internal/events/pb;pbb\x06proto3"

var (
	file_event_v1_event_proto_rawDescOnce sync.Once
	file_event_v1_event_proto_rawDescData []byte
)

func file_event_v1_event_proto_rawDescGZIP() []byte {
	file_event_v1_event_proto_rawDescOnce.Do(func() {
		file_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)))
	})
	return file_event_v1_event_proto_rawDescData
}

var file_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_event_v1_event_proto_goTypes = []any{
	(*Event)(nil), // 0: event.v1.Event
	nil,           // 1: event.v1.Event.BeforeEntry
	nil,           // 2: event.v1.Event.AfterEntry
}
var file_event_v1_event_proto_depIdxs = []int32{
	1, // 0: event.v1.Event.before:type_name -> event.v1.Event.BeforeEntry
	2, // 1: event.v1.Event.after:type_name -> event.v1.Event.AfterEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_event_v1_event_proto_init() }
func file_event_v1_event_proto_init() {
	if File_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_v1_event_proto_goTypes,
		DependencyIndexes: file_event_v1_event_proto_depIdxs,
		MessageInfos:      file_event_v1_event_proto_msgTypes,
	}.Build()
	File_event_v1_event_proto = out.File
	file_event_v1_event_proto_goTypes = nil
	file_event_v1_event_proto_depIdxs = nil
}
